import { useEffect, useMemo, useState } from 'react'
import { get, type Health, type Overview, type Page, type Row, type Session } from './api/client'
import './App.css'

const nav = [['/', 'Overview'], ['/sessions', 'Sessions'], ['/agents', 'Agents'], ['/tools', 'Tools'], ['/approvals', 'Governance'], ['/skills', 'Skills'], ['/git', 'Git'], ['/archive', 'Archive'], ['/health', 'Health']] as const
function Evidence({ value }: { value?: { source_class: string; fact_type: string } }) { return <span className="evidence" title={value ? `${value.fact_type} evidence` : 'Evidence unavailable'}>{value?.source_class ?? 'UNKNOWN'}</span> }
function State({ state }: { state: 'loading' | 'empty' | 'ready' | 'degraded' | 'error' }) { return <p className={`state ${state}`} role={state === 'error' ? 'alert' : 'status'}>{state.toUpperCase()}</p> }
function useApi<T>(path: string) { const [state, setState] = useState<{ value?: T; status: 'loading' | 'ready' | 'empty' | 'degraded' | 'error'; error?: string }>({ status: 'loading' }); useEffect(() => { const controller = new AbortController(); setState({ status: 'loading' }); get<T>(path, controller.signal).then(value => setState({ value, status: value && typeof value === 'object' && 'items' in value && !(value as {items: unknown[]}).items.length ? 'empty' : 'ready' })).catch(error => { if (error.name !== 'AbortError') setState({ status: 'error', error: error.message }) }); return () => controller.abort() }, [path]); return state }
function MetricCard({ label, metric }: { label: string; metric: { value: number | null; coverage: string; evidence?: { source_class: string; fact_type: string } | null } }) { return <article className="metric"><div className="metric-label">{label}</div><div className="metric-value">{metric.value ?? '—'}</div><div className="metric-meta">{metric.coverage} <Evidence value={metric.evidence ?? undefined} /></div></article> }
function PanelState({ state }: { state: { status: string; error?: string } }) { return <section className="panel"><State state={state.status as 'loading' | 'empty' | 'degraded' | 'error'} />{state.error && <p>{state.error}</p>}</section> }
function HealthPanel({ health }: { health: Health }) { return <section className="panel"><div className="panel-title"><h2>Evidence coverage</h2><Evidence value={{ source_class: 'OBSERVATORY', fact_type: 'component health' }} /></div><div className="health-grid">{health.components.map(c => <div className="health-item" key={c.component}><span className={`status-dot ${c.status}`}>{c.status}</span><strong>{c.component}</strong>{c.reason && <small>{c.reason}</small>}</div>)}</div></section> }
function OverviewView() { const state = useApi<Overview>('/overview'); if (state.status !== 'ready' || !state.value) return <PanelState state={state} />; const o = state.value; return <><div className="page-heading"><div><p className="eyebrow">LOCAL READ-ONLY OBSERVABILITY</p><h1>Overview</h1></div><span className={`status-dot ${o.health.status}`}>{o.health.status}</span></div><div className="metrics">{[['Sessions', o.sessions], ['Threads', o.threads], ['Turns', o.turns], ['Events', o.events], ['Tool calls', o.tool_calls], ['Tool failures', o.tool_failures], ['Approvals', o.approvals], ['Agents', o.agents], ['Tokens', o.tokens], ['Repositories', o.repositories]].map(([label, metric]) => <MetricCard key={label as string} label={label as string} metric={metric as Overview['sessions']} />)}</div><HealthPanel health={o.health} /><section className="panel"><h2>Archive</h2><p><strong>{o.archive.status}</strong> · {o.archive.batches} batches · {o.archive.files} files · {o.archive.rows} rows · DuckDB {o.archive.duckdb_status}</p></section></> }
function format(value: unknown) { if (value === null || value === undefined || value === '') return '—'; if (typeof value === 'boolean') return value ? 'yes' : 'no'; return String(value) }
function TableView({ title, endpoint, columns }: { title: string; endpoint: string; columns: string[] }) { const state = useApi<Page<Row>>(endpoint); if (state.status !== 'ready' || !state.value) return <><div className="page-heading"><h1>{title}</h1></div><PanelState state={state} /></>; return <><div className="page-heading"><div><p className="eyebrow">EVIDENCE-BACKED VIEW</p><h1>{title}</h1></div><span className="count">{state.value.items.length} shown</span></div><section className="panel table-wrap">{state.value.items.length === 0 ? <State state="empty" /> : <table><thead><tr>{columns.map(c => <th scope="col" key={c}>{c.replaceAll('_', ' ')}</th>)}<th scope="col">evidence</th></tr></thead><tbody>{state.value.items.map((row, i) => <tr key={String(row.id ?? row.thread_id ?? row.tool ?? row.repo_id ?? i)}>{columns.map(c => <td key={c} className={c.includes('id') || c.includes('sha') ? 'mono' : ''}>{format(row[c])}</td>)}<td><Evidence value={row.evidence} /></td></tr>)}</tbody></table>}</section></> }
function JsonView({ title, endpoint, fields }: { title: string; endpoint: string; fields: string[] }) { const state = useApi<Row>(endpoint); if (state.status !== 'ready' || !state.value) return <><div className="page-heading"><h1>{title}</h1></div><PanelState state={state} /></>; return <><div className="page-heading"><div><p className="eyebrow">READ-ONLY STATUS</p><h1>{title}</h1></div></div><section className="panel detail-grid">{fields.map(field => <div key={field}><small>{field.replaceAll('_', ' ')}</small><strong>{format(state.value?.[field])}</strong></div>)}</section></> }
function SessionsView() { const state = useApi<Page<Session>>('/sessions'); if (state.status !== 'ready' || !state.value) return <><div className="page-heading"><h1>Sessions</h1></div><PanelState state={state} /></>; return <><div className="page-heading"><div><p className="eyebrow">THREAD IDENTITY IS PRESERVED</p><h1>Sessions</h1></div></div><section className="panel table-wrap">{state.value.items.length ? <table><thead><tr>{['thread_id', 'model', 'started_at', 'status', 'turns', 'tokens', 'tool_calls'].map(c => <th scope="col" key={c}>{c.replace('_', ' ')}</th>)}</tr></thead><tbody>{state.value.items.map(s => <tr key={s.thread_id}><td className="mono"><a href={`/sessions/${encodeURIComponent(s.thread_id)}`}>{s.thread_id}</a></td><td>{format(s.model)}</td><td>{format(s.started_at)}</td><td>{format(s.status)}</td><td>{s.turns}</td><td>{format(s.tokens)}</td><td>{s.tool_calls}</td></tr>)}</tbody></table> : <State state="empty" />}</section></> }
function SessionDetail({ id }: { id: string }) { const state = useApi<Session>(`/sessions/${encodeURIComponent(id)}`); if (state.status !== 'ready' || !state.value) return <><div className="page-heading"><h1>Session detail</h1></div><PanelState state={state} /></>; const s = state.value; return <><div className="page-heading"><div><p className="eyebrow">THREAD / SESSION DETAIL</p><h1>{s.name || s.thread_id}</h1></div><Evidence value={s.evidence} /></div><section className="panel detail-grid">{Object.entries(s).filter(([key]) => key !== 'evidence').map(([key, value]) => <div key={key}><small>{key.replaceAll('_', ' ')}</small><strong className={key.endsWith('id') ? 'mono' : ''}>{format(value)}</strong></div>)}</section><TableView title="Timeline" endpoint={`/events?thread_id=${encodeURIComponent(s.thread_id)}`} columns={['event_time', 'category', 'name', 'status', 'thread_id']} /></> }
function App() { const [path, setPath] = useState(window.location.pathname); useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, []); const go = (url: string) => { history.pushState({}, '', url); setPath(url) }; const page = useMemo(() => { if (path.startsWith('/sessions/')) return <SessionDetail id={decodeURIComponent(path.slice('/sessions/'.length))} />; if (path === '/sessions') return <SessionsView />; if (path === '/agents') return <TableView title="Agents" endpoint="/agents" columns={['agent_id', 'parent_agent_id', 'agent_type', 'state', 'thread_id', 'tool_count']} />; if (path === '/tools') return <TableView title="Tools" endpoint="/tools" columns={['tool', 'calls', 'successes', 'failures', 'unknown_results']} />; if (path === '/approvals') return <TableView title="Governance / approvals" endpoint="/approvals" columns={['approval_id', 'decision', 'decision_source', 'tool', 'thread_id', 'observed_at']} />; if (path === '/skills') return <TableView title="Skills" endpoint="/skills" columns={['skill', 'status', 'thread_id', 'observed_at']} />; if (path === '/git') return <TableView title="Git evidence" endpoint="/git/snapshots" columns={['repo_id', 'head_sha', 'head_ref', 'head_state', 'clean', 'staged', 'unstaged', 'captured_at']} />; if (path === '/archive') return <JsonView title="Archive / analytics" endpoint="/archive/health" fields={['status', 'batches', 'files', 'rows', 'verification_failures', 'small_files', 'duckdb_status']} />; if (path === '/health') return <JsonView title="Health" endpoint="/health" fields={['status']} />; return <OverviewView /> }, [path]); return <div className="shell"><header><a className="brand" href="/" onClick={e => { e.preventDefault(); go('/') }}>CODEX <span>OBSERVATORY</span></a><nav aria-label="Primary navigation">{nav.map(([href, label]) => <a key={href} href={href} className={path === href ? 'active' : ''} onClick={e => { e.preventDefault(); go(href) }}>{label}</a>)}</nav></header><main>{page}</main><footer>Read-only local dashboard · HTTP API is authoritative · no prompts or raw payloads rendered</footer></div> }
export default App
